### ISSUE TITLE
Support global alt+ num short cut

### ISSUE THREAD

**Issue by newbe36524** [Amazing-Favorites/Amazing-Favorites#25]

**Comment by Z4t4r** [comment]
Google Chrome: maximum of 4 chrome.commands allowed
https://stackoverflow.com/questions/14000217/google-chrome-maximum-of-4-chrome-commands-allowed/14000881

**Comment by newbe36524** [comment]
Thank you very much for your research.
I think it was because you had to be on the manager page with the input box selected for the shortcut to work. Now it seems that this problem is no longer there and it works even if the input box has no focus.
closed
