### ISSUE TITLE
Support keyboard event for feature #20

### ISSUE THREAD

**Issue by newbe36524** [Amazing-Favorites/Amazing-Favorites#50]
Support keyboard event for feature #20

**Comment by Z4t4r** [comment]
This feature is already available [#45 ](https://github.com/Amazing-Favorites/Amazing-Favorites/blob/751a5f2fcc61d51e7d4592b6ce6813525edd7228/src/Newbe.BookmarkManager/Pages/Manager.cs#L359-L376)

**Comment by newbe36524** [comment]
我想，这应该是指，通过单纯的键盘操作来实现一样的效果

**Comment by Z4t4r** [comment]
好像只有Alt + Num比较合理, 原来的active已经使用这个组合了,open new one暂时没找到合适的组合方式

**Comment by newbe36524** [comment]
那么就放弃
